### PR TITLE
Handles multiple_icon sites that dont support xml fixes #97

### PR DESCRIPTION
**Pull request by Taz17**
This solves the issue with Northern Beaches council in the multiple_icon scraper.

Issue [#97](https://github.com/planningalerts-scrapers/issues/issues/97) has been open since July 2020 and @katska reached out to the council in Dec 6 2021 about `&o=xml` issue.

Code is written so that it checks attempts to scrape XML version first and if it fails then it attempts to scrape the html. This way, if the council ever updates the issue the program will continue with the XML scraping.

### CODE REVIEW

**Comment by mlandauer** [comment]
@Taz17 Looks to me that the `info_url` isn't right. It should be a full path. It should look something like `https://eservices.northernbeaches.nsw.gov.au/ePlanning/live/Public/XC.Track/SearchApplication.aspx?id=1661167` but instead looks like `SearchApplication.aspx?id=2046095`.

Is there any way to make the `description` closer to the form it had before when we could get the data via xml? I'm guessing not but if it were possible that would be great.

Also, don't forget to update the regression tests. Everything should pass when `bundle exec rake` is run

**Comment by Taz17** [comment]
@mlandauer Is there a way to automatically update the regression tests? I am currently doing it manually which does not feel right

**Comment by mlandauer** [comment]
> @mlandauer Is there a way to automatically update the regression tests? I am currently doing it manually which does not feel right

You can run the tests and it will error and actually overwrite the expected result. So you can just do a `git diff` to see the difference and eye ball it to make sure it's what's expected.

If the data that is being scraped is different and so the recording of the web requests is out of date you can just delete the relevant file in vcr_cassettes and rerun the tests.

**Comment by Taz17** [comment]
Ah i see, deleting the file in vcr_cassettes re-created the file. However, running the tests did not overwrite the expected result for some reason.

Anyways should be good to review again now.

**Comment by mlandauer** [comment]
Thanks @Taz17

**Pull request merged**
